### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by trevoruptain** [Tsanta96/MusicBox#1]
Great work on your proposal, and especially on your implementation timeline. Please add some more detail to your Background & Overview section - what is your motivation for making this app, why is it interesting, and what qualities would make it interesting to a visitor such as a recruiter? 

Who is doing what over the weekend? Are you all working together on the initial setup or splitting up tasks? Let me know.

**Comment by Tsanta96** [comment]
Thanks! Okay we'll add more to the background now. In regards to weekend work, Derek is doing backend Auth and AWS S3 setup (if we can't get to it today), Nick is seeding the database, creating the necessary models, setting up the mongoose schema, and styling. If we finish all of this, which there's a good chance we will, we'll begin working on our respective tasks for the next day's work that we have detailed in the breakdown
